# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8080
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: monteiro
      ME_CONFIG_MONGODB_ADMINPASSWORD: monteiro
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/